name: Storybook deploy

on:
  push:
    branches: - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Deploy storybook to GitHub Pages
        run: |
          yarn
          yarn storybook build
          yarn storybook deploy
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}