name: Storybook
on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          yarn
          yarn run build-storybook
          yarn run deploy-storybook
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}
